# This workflow runs whenever a PR is created or commits are pushed to it
name: test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - run: yarn test