name: run test
on:
  pull_request:
    branches:
    - master
    types:
    - synchronize
    - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Create a folder in the gh-pages branch
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          git checkout -b gh-pages
          mkdir $BRANCH
          touch $BRANCH/index.html
          echo "<h1> Hello World from ${BRANCH}" > $BRANCH/index.html
          git config --local user.email "scanner@peak.ai"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add file for ${BRANCH}"
          git push origin gh-pages    
