name: run test
on:
  pull_request:
    branches:
    - master
    types:
    - synchronize
    - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - name: Run tests
        id: test
        run: |
          yarn test &> test-result.txt
      - name: Add Env
        id: add_test_res
        if: ${{ success() || (failure() && steps.test.outcome == 'failure') }}
        run: |
          echo 'TEST_RES<<EOF' >> $GITHUB_ENV
          cat test-result.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Add comment
        if: ${{ success() || (failure() && steps.test.outcome == 'failure' && steps.add_test_res.outcome == 'success') }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            I am your beautiful *Test Runner* :elf:
            I ran the tests and found it ${{ steps.test.outcome == 'success' && 'was Successfull :tada:' || 'Failed :cry:'   }}
            Here are the results:
            ```
            ${{ env.TEST_RES }}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true