name: test
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: 'dev'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ github.event.inputs.stage }}
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Set Output
        id: set_output
        run: |
          echo $STAGE