name: test
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: 'dev'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ github.event.inputs.stage }}
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Set Output
        id: set_output
        run: |
          echo $STAGE
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - run: yarn test
      - name: Notify on Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: author,message,workflow
          custom_payload: |
            {
              "attachments": [
                {
                  "color": '${{ job.status }}' === 'success' ? 'good' : 'danger',
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": ('${{ job.status }}' === 'success' ? ':partydeploy:' : ':warning:') +
                          ' *service-${{ env.STAGE }}* : Service Deployment ' +
                          ('${{ job.status }}' === 'success' ? 'was Successful.' : '${{ job.status }}' === 'cancelled' ? 'was Cancelled.' : 'has Failed.')
                      },
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": `Commit Message\n${process.env.AS_MESSAGE}`
                        },
                        {
                          "type": "mrkdwn",
                          "text": `Branch\n${process.env.AS_AUTHOR}`,
                        },
                        {
                          "type": "mrkdwn",
                          "text": "Author\n${process.env.AS_AUTHOR}"
                        }
                      ]
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "Check Deployment Logs",
                            "emoji": true
                          },
                          "value": "click_me_123",
                          "url": `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: https://webhook.site/251ce8c6-8160-462c-8c88-6a85e58bf13e
