name: test
on:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build . -t hello-world
      - name: Check Images
        run: |
          docker images