name: test
on:
  pull_request:
    branches:
    - master
    types:
    - synchronize
    - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - name: Run tests
        id: test
        run: |
          yarn test &> test-result.txt
          echo "::set-output name=testResult::`cat test-result.txt`"
      - name: Add comment
        if: always()
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            I ran the test, here are the results
            ```
            ${{ steps.test.outputs.testResult }}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}